name: Build Yocto Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Yocto DevContainer Image
        run: docker pull ghcr.io/emblincram/boxy:latest

      - name: Run Yocto Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/emblincram/boxy:latest /bin/bash -c "
            cd /workspace
            source poky/oe-init-build-env build
            bitbake core-image-minimal
          "

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yocto-build
          path: build/tmp/deploy/images/
